import { getDb } from "@/lib/db";

export const dynamic = "force-dynamic";

// The desktop/CLI agent calls this to publish its track list + liveness.
// Auth is a per-artist agent_key (Bearer), generated by the artist in /account.
// Body: { tracks, tunnelUrl?, named? }
//   - named: true (token-mode agent) -> the liveness marker is the provisioned media_origin;
//     the agent doesn't know or need the public host.
//   - tunnelUrl (legacy quick-tunnel agent) -> stored as the liveness marker directly.

type IncomingTrack = {
  title: string;
  filename: string;
  duration?: string;
  featured?: boolean;
};

export async function POST(req: Request) {
  const json = (code: number, body: unknown) =>
    new Response(JSON.stringify(body), {
      status: code,
      headers: { "Content-Type": "application/json" },
    });

  const auth = req.headers.get("authorization") || "";
  const key = auth.replace(/^Bearer\s+/i, "").trim();
  if (!key) return json(401, { error: "Missing agent key" });

  const db = getDb();
  const artist = await db
    .prepare("SELECT slug, media_origin FROM artist_profiles WHERE agent_key = ? LIMIT 1")
    .bind(key)
    .first<{ slug: string; media_origin: string | null }>();
  if (!artist) return json(403, { error: "Invalid agent key" });

  let body: { tunnelUrl?: string; tracks?: IncomingTrack[]; named?: boolean };
  try {
    body = (await req.json()) as { tunnelUrl?: string; tracks?: IncomingTrack[]; named?: boolean };
  } catch {
    return json(400, { error: "Invalid body" });
  }
  // Resolve the liveness marker. Token-mode (named) agents derive it from the provisioned
  // host; legacy quick-tunnel agents send their trycloudflare URL directly.
  let tunnelUrl: string;
  if (body.named) {
    if (!artist.media_origin) return json(409, { error: "Streaming not set up; provision first" });
    tunnelUrl = `https://${artist.media_origin}`;
  } else {
    tunnelUrl = (body.tunnelUrl ?? "").trim();
    if (!tunnelUrl) return json(400, { error: "tunnelUrl required" });
  }
  const tracks = Array.isArray(body.tracks) ? body.tracks : [];

  const now = new Date().toISOString();
  await db
    .prepare("UPDATE artist_profiles SET tunnel_url = ?, updated_at = ? WHERE slug = ?")
    .bind(tunnelUrl, now, artist.slug)
    .run();

  // Replace the artist's self-hosted track list with what the agent reports.
  await db.prepare("DELETE FROM tracks WHERE artist_slug = ? AND source = 'self'").bind(artist.slug).run();
  let sort = 0;
  for (const t of tracks) {
    if (!t || !t.title || !t.filename) continue;
    await db
      .prepare(
        "INSERT INTO tracks (artist_slug, title, filename, duration, is_featured, sort, source, created_at) VALUES (?, ?, ?, ?, ?, ?, 'self', ?)"
      )
      .bind(
        artist.slug,
        t.title,
        t.filename,
        t.duration ?? null,
        t.featured ? 1 : 0,
        sort++,
        now
      )
      .run();
  }

  return json(200, { ok: true, slug: artist.slug, tracks: tracks.length });
}
